server:
  port: 8082
spring:
  application:
    name: user-api
  data:
    mongodb:
      host: ip-172-31-45-181.ap-northeast-2.compute.internal
      port: 27017
      database: user
      username: admin
      password: secret
      authentication-database: admin
  rabbitmq:
    host: 15.164.133.223
    port: 5672
    username : admin
    password: secret
logging:
  config: classpath:logback/logback-spring.xml #BOOT-INF/classes/logback/logback-spring.xml
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

