server {
    listen 80;
    server_name real-insight.kr www.real-insight.kr;
    root /usr/share/nginx/html;
    index city.html;

    location = / {
        return 302 /city.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}